---
title: "Policy Text Analysis"
author: "Samantha"
format: html
editor: visual
---

#Libraries
```{r}
library(tidyverse)
library(tidytext)
library(pdftools)
library(here)
library(textdata)
library(patchwork)
```

#read in data
```{r}
policy_2023_text <- pdftools::pdf_text(here('data', 'bills_2023_all.pdf'))

policy_2024_text <- pdftools::pdf_text(here('data', 'bills_2024_all.pdf'))
```

Create Tokens
```{r}
#######2023
p_2023_lines <- data.frame(policy_2023_text) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(policy_2023_text, pattern = '\\n')) %>% 
  unnest(text_full) %>% 
  mutate(text_full = str_trim(text_full)) %>% 
 unnest_tokens(word, text_full) %>% 
  anti_join(stop_words, by = 'word') 

head(stop_words)

wordcount_clean_2023 <- p_2023_lines %>% 
  anti_join(stop_words, by = 'word')

######2024
p_2024_lines <- data.frame(policy_2024_text) %>% 
  mutate(page = 1:n()) %>%
  mutate(text_full = str_split(policy_2024_text, pattern = '\\n')) %>% 
  unnest(text_full) %>% 
  mutate(text_full = str_trim(text_full)) %>% 
  unnest_tokens(word, text_full) %>% 
  anti_join(stop_words, by = 'word') 

head(stop_words)

wordcount_clean_2024 <- p_2024_lines %>% 
  anti_join(stop_words, by = 'word')

```

top ten words #not working might work after joining the sentiment word thing
```{r}
top_5_2023_words <- wordcount_clean_2023 %>% 
  group_by(word) %>% 
  arrange(-n) %>% 
  slice(1:10) %>%
  ungroup()
```
 

Sentiment Annalysis
```{r}
nrc_lex <- get_sentiments(lexicon = "nrc")

#########2023 
p_2023_nrc <- wordcount_clean_2023 %>% 
  inner_join(nrc_lex, by = 'word') 

p_2023_counts <- p_2023_nrc %>% 
  group_by(sentiment) %>%
  summarize(n = n()) %>%
  mutate(percent = (n/sum(n))*100)

############2024

p_2024_nrc <- wordcount_clean_2024 %>% 
  inner_join(nrc_lex, by = 'word') 

p_2024_counts <- p_2024_nrc %>% 
  group_by(sentiment) %>%
  summarize(n = n()) %>%
  mutate(percent = (n/sum(n))*100)
```
Sentiment graphs
```{r}
######2023
sentiment_2023_plot <- ggplot(data = p_2023_counts, aes(x = sentiment, y = percent)) +
  geom_col(fill = "darkblue") +
  labs(title = "2023 Policy Sentiment Analysis",
       x = 'Sentiment',
       y= 'Percent of All Words') +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

sentiment_2023_plot

######2024
sentiment_2024_plot <- ggplot(data = p_2024_counts, aes(x = sentiment, y = percent)) +
  geom_col(fill = "darkblue") +
  labs(title = "2024 Policy Sentiment Analysis",
       x = 'Sentiment',
       y= 'Percent of All Words') +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

sentiment_2024_plot

sentiment_combined <- (sentiment_2023_plot + sentiment_2024_plot)
sentiment_combined



ggsave(here("Plots", "sentiment_combined.jpg"), sentiment_combined, width=8,
       height=6, units="in", dpi=800)
```



